## GOJEK

### Import Library

In [1]:
import pandas as pd
import re

### Load Dataset

In [63]:
df_gojek = pd.read_csv('../data/kotor/gojek_reviews.csv')
df_gojek.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,apps
0,6083605b-7faa-4eae-aa8c-cbff9c9f5398,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,"ga jelas, bertahun-tahun pake tiba-tiba dibilang pelanggaran promo. padahal mereka sendiri yang munculin promo di app di pake malah dibilang melanggar",1,0,NaN,2026-06-21 08:55:15,"Hai Kak Ahmad, mohon maaf atas ketidaknyamannya. Untuk bantu pengecekan akun yang dibekukan, silakan masuk ke aplikasi Gojek lalu ke Profil > Bantuan > Masalah dengan Akun Saya > ""Akun saya dibekukan"" > isi formulir. Kami tunggu detail kendalanya ya. ^Maysa",2026-06-21 09:17:57,NaN,Gojek
1,e4fb4a88-e8ef-42f1-989e-8ad1bb195c36,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,semakin kesini kok lebih parah dari lintah darat. disaat semua kebutuhan naik perawatan kendaraan juga naik tarif ke driver malah turun. semoga Allah memberikan kalian hidayah aamiin,1,0,5.63.1,2026-06-21 08:39:41,"Hai Kak Muhlas, terima kasih atas ulasannya dan mohon maaf untuk kendalanya. Laporan yang Kakak sampaikan akan menjadi masukan bagi kami untuk terus meningkatkan kualitas layanan kami ke depannya. Jika Kakak memiliki pertanyaan atau kendala lainnya, silakan kunjungi menu Bantuan di aplikasi Gojek Driver App kamu. ^Maysa",2026-06-21 09:11:08,5.63.1,Gojek
2,0bd033c1-d662-4c10-9ccc-5f04418060e8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,kelas king,5,0,NaN,2026-06-21 08:36:28,NaN,NaN,NaN,Gojek
3,3841810d-ac6a-4046-9f65-370457076d57,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,ramah,5,0,5.63.1,2026-06-21 08:29:51,NaN,NaN,5.63.1,Gojek
4,f5e00323-0665-4f48-8bbc-7636a499ed67,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,memuaskan,5,0,5.61.1,2026-06-21 08:13:56,NaN,NaN,5.61.1,Gojek

### EDA (Exploratory Data Analis)

In [64]:
num_gojek = len(df_gojek)
print(f"Jumlah ulasan dalam dataframe {num_gojek} data")

Jumlah ulasan dalam dataframe 10000 data

In [65]:
df_gojek_test = df_gojek.copy()
df_gojek_test

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,apps
0,6083605b-7faa-4eae-aa8c-cbff9c9f5398,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,"ga jelas, bertahun-tahun pake tiba-tiba dibilang pelanggaran promo. padahal mereka sendiri yang munculin promo di app di pake malah dibilang melanggar",1,0,NaN,2026-06-21 08:55:15,"Hai Kak Ahmad, mohon maaf atas ketidaknyamannya. Untuk bantu pengecekan akun yang dibekukan, silakan masuk ke aplikasi Gojek lalu ke Profil > Bantuan > Masalah dengan Akun Saya > ""Akun saya dibekukan"" > isi formulir. Kami tunggu detail kendalanya ya. ^Maysa",2026-06-21 09:17:57,NaN,Gojek
1,e4fb4a88-e8ef-42f1-989e-8ad1bb195c36,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,semakin kesini kok lebih parah dari lintah darat. disaat semua kebutuhan naik perawatan kendaraan juga naik tarif ke driver malah turun. semoga Allah memberikan kalian hidayah aamiin,1,0,5.63.1,2026-06-21 08:39:41,"Hai Kak Muhlas, terima kasih atas ulasannya dan mohon maaf untuk kendalanya. Laporan yang Kakak sampaikan akan menjadi masukan bagi kami untuk terus meningkatkan kualitas layanan kami ke depannya. Jika Kakak memiliki pertanyaan atau kendala lainnya, silakan kunjungi menu Bantuan di aplikasi Gojek Driver App kamu. ^Maysa",2026-06-21 09:11:08,5.63.1,Gojek
2,0bd033c1-d662-4c10-9ccc-5f04418060e8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,kelas king,5,0,NaN,2026-06-21 08:36:28,NaN,NaN,NaN,Gojek
3,3841810d-ac6a-4046-9f65-370457076d57,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,ramah,5,0,5.63.1,2026-06-21 08:29:51,NaN,NaN,5.63.1,Gojek
4,f5e00323-0665-4f48-8bbc-7636a499ed67,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g,memuaskan,5,0,5.61.1,2026-06-21 08:13:56,NaN,NaN,5.61.1,Gojek
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2553e26b-d7c5-444a-8d1d-bd41bcb429f6,Novita Miradewi,https://play-lh.googleusercontent.com/a/ACg8ocJpEC549W8wWbumlUoGIaHacGjQOu8VjKw0aljMez-EeMOQKw=mo,bagus,5,0,5.53.2,2026-04-03 09:02:32,NaN,NaN,5.53.2,Gojek
9996,be8d2909-54f3-42ed-91d7-f2e6ee9f20c1,Arif Bowox,https://play-lh.googleusercontent.com/a/ACg8ocIuYmu2a-cT7ldBtG17iixsTWITel3c1mXO5w5YfykyDUMjlw=mo,baik sekali,5,0,NaN,2026-04-03 08:54:33,NaN,NaN,NaN,Gojek
9997,0fec53f4-642b-4501-a678-5341ff6de6ba,Febri Cs,https://play-lh.googleusercontent.com/a/ACg8ocIVz7-qMYZdAiMKdp3qkmBHM-d6DA8Akrte_l08heWUiPfnNQ=mo,segini dlu deh klo bagus tambah lagi,2,0,NaN,2026-04-03 08:44:03,NaN,NaN,NaN,Gojek
9998,1758ee03-5b00-4cc1-9429-7a01475d32c7,Moses Sudanartha,https://play-lh.googleusercontent.com/a-/ALV-UjV4MQv8KMpaXANMouzutbDqMEOu2-P0788Zc6snd87P3C0VWP6-,Drivernya tolong jangan memainkan orderan. ditunggu sangat lama tidak jalan sama sekali. Apkikasinya sering mengalami bug double order. bikin saya repot.,1,3,5.54.1,2026-04-03 08:41:20,"Hai Kak Moses, mohon maaf atas ketidaknyamanannya. Laporan yang kamu berikan akan menjadi masukan bagi kami untuk terus meningkatkan kualitas pelayanan kami ke depannya. Jika kamu memiliki pertanyaan atau kendala lainnya, silakan kunjungi menu Bantuan di aplikasi Gojek kamu. ^Melodi",2026-04-03 09:09:26,5.54.1,Gojek
9999,7616ec3b-90ea-4270-9036-76cd619f9b68,Supena,https://play-lh.googleusercontent.com/a-/ALV-UjVleODWBPZEdSHupHkRhm9Gupbx3P9KM2u9N4nqDLUn_fWGUyxQ,terima kasih,5,0,5.54.1,2026-04-03 08:39:56,NaN,NaN,5.54.1,Gojek

In [66]:
pd.set_option('display.max_colwidth', None)
df_gojek_test['content'].head(5)

0                                    ga jelas, bertahun-tahun pake tiba-tiba dibilang pelanggaran promo. padahal mereka sendiri yang munculin promo di app di pake malah dibilang melanggar
1    semakin kesini kok lebih parah dari lintah darat. disaat semua kebutuhan naik perawatan kendaraan juga naik tarif ke driver malah turun. semoga Allah memberikan kalian hidayah aamiin
2                                                                                                                                                                                kelas king
3                                                                                                                                                                                     ramah
4                                                                                                                                                                                 memuaskan
Name: content, dtype: object

In [67]:
# Cek missing value
print(f"Jumlah missing value pada kolom 'content': {df_gojek['content'].isnull().sum()}")

Jumlah missing value pada kolom 'content': 0

### Preprocesing

##### Import Stopword Indonesia

In [2]:
import requests
stopwords_url = "https://raw.githubusercontent.com/louisowen6/NLP_bahasa_resources/master/combined_stop_words.txt"

response = requests.get(stopwords_url)

stopwords = response.text.splitlines()

stopwords = set(stopwords)

print(list(stopwords)[:10])

['diantara', 'belumlah', 'dimaksud', 'nggak', 'sekaligus', 'tepat', 'sesegera', 'siapakah', 'haruslah', 'pihaknya']

In [3]:
kata_negasi = ['tidak', 'bukan', 'ga', 'gk', 'jangan']
for kata in kata_negasi:
    if kata in stopwords:
        stopwords.remove(kata)

##### Import Slang Indonesia

In [4]:
import json

slang_url = "https://raw.githubusercontent.com/louisowen6/NLP_bahasa_resources/master/combined_slang_words.txt"

response = requests.get(slang_url)

kamus_slang_custom = response.json()

kamus_slang_custom.update({
    'tbtb': 'tiba tiba',
    'gk': 'tidak',
    'kdng': 'kadang'
})

print("Total kata di kamus baru:", len(kamus_slang_custom))
print("Contoh isi kamus (tbtb):", kamus_slang_custom['tbtb'])

Total kata di kamus baru: 1021
Contoh isi kamus (tbtb): tiba tiba

#### Cleaning

In [12]:
def clean_string(text):
    text = str(text)

    # 1. Remove Metadata & Footer Removal
    text = text.strip()

    # 2. Remove URL
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # 3. Lowercase
    text = text.lower()

    # 4. Remove Numbers
    text = re.sub(r'\d+', ' ', text)

    # 5. Remove Punctuation (Menghapus tanda baca & simbol/emoji)
    text = re.sub(r'[^a-z\s]', ' ', text)

    # 6. Merapikan spasi berlebih hasil pembersihan
    text = ' '.join(text.split())

    return text

In [13]:
# Pembersihan Berbasis Kata (Tokens)

def process_tokens(cleaned_sentence):
    text = str(cleaned_sentence).lower()
    # Tokenization
    tokens = text.split()

    final_tokens = []
    for token in tokens:
        token = token.strip()

        # Normalisasi Slang
        if token in kamus_slang_custom:
            token = kamus_slang_custom[token]

        # Stopword Removal
        if token not in stopwords:
            final_tokens.append(token)

    # Mengembalikan hasil akhir dalam bentuk kalimat bersih atau list token
    return ' '.join(final_tokens)

In [73]:
# Membersihkan String
df_gojek_test['step1_string'] = df_gojek_test['content'].apply(clean_string)

# Olah token dan normalisasinya
df_gojek_test['clean_content'] = df_gojek_test['step1_string'].apply(process_tokens)

# Perbandingannya
print(df_gojek_test[['content', 'clean_content']].head(100))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content  \
0                                                                                                                                                                                                                                                                                                                                                                ga jelas, bertahun-tahun pake tiba-tiba dibilang pelanggaran promo. padahal mereka sendiri yang munculin promo di app di pake malah dibilang melanggar
1                                                                                                                                                                                                                                                                                                                                semakin kesini kok lebih parah dari lintah darat. disaat semua kebutuhan naik perawatan kendaraan juga naik tarif ke driver malah turun. semoga Allah memberikan kalian hidayah aamiin
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            kelas king
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ramah
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             memuaskan
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...
95                                                                                                                                                                                                                                                                                                                                                                                                                     desain simple gk membingungkan,pelayanan oke,cocok buat siapa aja dan yang pasti BUATAN NEGRI🔥🔥🔥
96                                                                                                                                                                                                                                                                                                                                                                                                                                   Ayolah jangan bikin iklan d aplikasi lain yang gk bisa d skip. ganggu banget !!!!!
97  Selama ini jujur saya sangat puas dengan gojek, membantu ketika saya bepergian karena saya seringkali bepergian menggunakan umum. tetapi hal menyebalkan terjadi, ketika saya sedang mendengarkan sesuatu diaplikasi lain dan hp saya taruh tas, ntah gimana ceritanya tbtb ada pesanan gofood yg masuk tanpa konfirmasi apapun. gak ada masukan pin atau sejenisnya. saya setelah buka hp tbtb udh ada pesanan. sekarang mau dibatalkan gak bisa, alhasil mau gak mau harus di bayar. Thanks for bad experiencenya
98                                                                                                                                                                                                                                                                                                                                                                                                                                                     enak sih kalo mager tinggal pesen aja, tapi ongkirnya kdng mahal
99                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top

                                                                                                                                                                                                                                                                                                clean_content
0                                                                                                                                                                                                                    ga bertahun pakai dibilang pelanggaran promo munculin promo app pakai dibilang melanggar
1                                                                                                                                                                                               kesini parah lintah darat disaat kebutuhan perawatan kendaraan tarif driver turun semoga allah hidayah aamiin
2                                                                                                                                                                                                                                                                                                  kelas king
3                                                                                                                                                                                                                                                                                                       ramah
4                                                                                                                                                                                                                                                                                                   memuaskan
..                                                                                                                                                                                                                                                                                                        ...
95                                                                                                                                                                                                                                         desain simple tidak membingungkan pelayanan oke cocok buatan negri
96                                                                                                                                                                                                                                                ayolah jangan bikin iklan aplikasi tidak skip ganggu banget
97  jujur puas gojek bepergian seringkali bepergian menggunakan menyebalkan mendengarkan diaplikasi hp taruh tas ntah ceritanya tiba tiba pesanan gofood masuk konfirmasi apapun gak masukan pin sejenisnya buka hp tiba tiba udh pesanan dibatalkan gak alhasil gak bayar terima kasih for bad experiencenya
98                                                                                                                                                                                                                                                                enak sih mager pesen ongkirnya kadang mahal
99                                                                                                                                                                                                                                                                                                        top

[100 rows x 2 columns]

#### Labeling

In [5]:
!pip install vaderSentiment deep-translator

Requirement already satisfied: vaderSentiment in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.3.2)
Requirement already satisfied: deep-translator in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.11.4)
Requirement already satisfied: requests in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from deep-translator) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (2025.8.3)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [75]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from deep_translator import GoogleTranslator
from tqdm import tqdm

# Inisialisasi SentimentIntensityAnalyzer dan GoogleTranslator
analyzer = SentimentIntensityAnalyzer()
translator = GoogleTranslator(source='id', target='en')

tanyain_teks = df_gojek_test['clean_content'].fillna("").astype(str).tolist()

hasil_terjemahan = []
batch_size = 100

print("Memulai proses translasi berbasis batch...")
for i in tqdm(range(0, len(tanyain_teks), batch_size)):
    batch = tanyain_teks[i:i+batch_size]
    try:
        # Masukkan list berisi 100 teks, hasil outputnya juga list berisi 100 terjemahan
        translated_batch = translator.translate_batch(batch)
        hasil_terjemahan.extend(translated_batch)
    except Exception as e:
        # Jaring pengaman jika satu batch gagal, isi dengan teks kosong agar ukuran list tetap singkron
        hasil_terjemahan.extend([""] * len(batch))

Memulai proses translasi berbasis batch...

100%|██████████| 100/100 [2:03:34<00:00, 74.14s/it]

In [76]:
def hitung_vader_dari_en(teks_en):
    if not teks_en or teks_en.strip() == "":
        return 'netral'
    scores = analyzer.polarity_scores(teks_en)
    compound = scores['compound']
    if compound >= 0.05: return 'positif'
    elif compound <= -0.05: return 'negatif'
    else: return 'netral'

# Petakan hasil terjemahan langsung ke kolom sentimen
df_gojek_test['sentimen'] = [hitung_vader_dari_en(t) for t in hasil_terjemahan]

In [77]:
df_gojek_test[['content', 'clean_content', 'sentimen']].head(100)

,content,clean_content,sentimen
0,"ga jelas, bertahun-tahun pake tiba-tiba dibilang pelanggaran promo. padahal mereka sendiri yang munculin promo di app di pake malah dibilang melanggar",ga bertahun pakai dibilang pelanggaran promo munculin promo app pakai dibilang melanggar,negatif
1,semakin kesini kok lebih parah dari lintah darat. disaat semua kebutuhan naik perawatan kendaraan juga naik tarif ke driver malah turun. semoga Allah memberikan kalian hidayah aamiin,kesini parah lintah darat disaat kebutuhan perawatan kendaraan tarif driver turun semoga allah hidayah aamiin,positif
2,kelas king,kelas king,netral
3,ramah,ramah,positif
4,memuaskan,memuaskan,positif
...,...,...,...
95,"desain simple gk membingungkan,pelayanan oke,cocok buat siapa aja dan yang pasti BUATAN NEGRI🔥🔥🔥",desain simple tidak membingungkan pelayanan oke cocok buatan negri,negatif
96,Ayolah jangan bikin iklan d aplikasi lain yang gk bisa d skip. ganggu banget !!!!!,ayolah jangan bikin iklan aplikasi tidak skip ganggu banget,negatif
97,"Selama ini jujur saya sangat puas dengan gojek, membantu ketika saya bepergian karena saya seringkali bepergian menggunakan umum. tetapi hal menyebalkan terjadi, ketika saya sedang mendengarkan sesuatu diaplikasi lain dan hp saya taruh tas, ntah gimana ceritanya tbtb ada pesanan gofood yg masuk tanpa konfirmasi apapun. gak ada masukan pin atau sejenisnya. saya setelah buka hp tbtb udh ada pesanan. sekarang mau dibatalkan gak bisa, alhasil mau gak mau harus di bayar. Thanks for bad experiencenya",jujur puas gojek bepergian seringkali bepergian menggunakan menyebalkan mendengarkan diaplikasi hp taruh tas ntah ceritanya tiba tiba pesanan gofood masuk konfirmasi apapun gak masukan pin sejenisnya buka hp tiba tiba udh pesanan dibatalkan gak alhasil gak bayar terima kasih for bad experiencenya,negatif
98,"enak sih kalo mager tinggal pesen aja, tapi ongkirnya kdng mahal",enak sih mager pesen ongkirnya kadang mahal,netral
99,top,top,positif

In [78]:
df_gojek_test['sentimen'].value_counts()

sentimen
positif    5579
netral     2586
negatif    1835
Name: count, dtype: int64

In [79]:
df_gojek_test.to_csv('gojek_review_bersih.csv', index=False)

# Grab

#### Load Dataset

In [6]:
df_grab = pd.read_csv('../data/kotor/grab_reviews.csv')
df_grab.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,apps
0,5137db44-22bd-4f77-8370-0d85d183507d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat membantu,5,0,5.414.0,2026-06-21 08:44:38,NaN,NaN,5.414.0,Grab
1,e1bc2bab-2922-48a6-a1e6-ff33c7d207f4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,oke gass,5,0,5.414.0,2026-06-21 08:38:39,NaN,NaN,5.414.0,Grab
2,8f57de7e-a6ed-4a91-a5b4-c6fc519208f3,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi andalan kalau mau pergi-pergi. Nyari ...,5,0,5.414.0,2026-06-21 08:38:33,NaN,NaN,5.414.0,Grab
3,33c314cb-f574-4bf2-800a-bef086201a56,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,good,5,0,NaN,2026-06-21 08:37:53,NaN,NaN,NaN,Grab
4,7161ae81-4608-46a1-b4da-c79dfc6ccec5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,semakin kesini semakin ga ngotak tarifnya. ket...,1,0,5.415.0,2026-06-21 08:37:39,Halo Kak. Maaf ya buat enggak nyaman 🙇‍♀️\nApa...,2026-06-21 13:12:57,5.415.0,Grab

#### EDA

In [7]:
num_grab = len(df_grab)
print(f"Jumlah ulasan dalam dataframe {num_grab} data")

Jumlah ulasan dalam dataframe 10000 data

In [8]:
df_grab_test = df_grab.copy()
df_grab_test

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,apps
0,5137db44-22bd-4f77-8370-0d85d183507d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat membantu,5,0,5.414.0,2026-06-21 08:44:38,NaN,NaN,5.414.0,Grab
1,e1bc2bab-2922-48a6-a1e6-ff33c7d207f4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,oke gass,5,0,5.414.0,2026-06-21 08:38:39,NaN,NaN,5.414.0,Grab
2,8f57de7e-a6ed-4a91-a5b4-c6fc519208f3,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi andalan kalau mau pergi-pergi. Nyari ...,5,0,5.414.0,2026-06-21 08:38:33,NaN,NaN,5.414.0,Grab
3,33c314cb-f574-4bf2-800a-bef086201a56,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,good,5,0,NaN,2026-06-21 08:37:53,NaN,NaN,NaN,Grab
4,7161ae81-4608-46a1-b4da-c79dfc6ccec5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,semakin kesini semakin ga ngotak tarifnya. ket...,1,0,5.415.0,2026-06-21 08:37:39,Halo Kak. Maaf ya buat enggak nyaman 🙇‍♀️\nApa...,2026-06-21 13:12:57,5.415.0,Grab
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,173f2bdb-7708-4e0c-8ddb-d13c7252b3cb,Yus Sulchan,https://play-lh.googleusercontent.com/a/ACg8oc...,"nyaman,semoga saya kedepnyaa dapet car(mobil)",5,0,NaN,2026-03-03 12:37:44,NaN,NaN,NaN,Grab
9996,2f9101ea-12c2-4b38-a771-42e646e03d7b,Jordy K,https://play-lh.googleusercontent.com/a-/ALV-U...,cukup bagus,5,0,5.399.0,2026-03-03 12:36:58,NaN,NaN,5.399.0,Grab
9997,fcd775e9-e2e7-40dc-9357-17b836e506c1,Kak Veee,https://play-lh.googleusercontent.com/a-/ALV-U...,males lah cukup tau kejadian hari ini sekian t...,1,0,NaN,2026-03-03 12:33:13,NaN,NaN,NaN,Grab
9998,23b1e464-12ec-4024-a0fd-99bfaa489152,Kevin lieonardi,https://play-lh.googleusercontent.com/a-/ALV-U...,"Grab update buat resto yang lama, sudah nnggu ...",1,1,5.399.0,2026-03-03 12:29:25,NaN,NaN,5.399.0,Grab
9999,7325bbce-24d8-4366-b3e0-3f0c666484ed,Mey yohana,https://play-lh.googleusercontent.com/a/ACg8oc...,Drivernya ramah,5,0,5.399.0,2026-03-03 12:24:36,NaN,NaN,5.399.0,Grab

In [9]:
pd.set_option('display.max_colwidth', None)
df_grab_test['content'].head(5)

0                                                                                                                                                                                               sangat membantu
1                                                                                                                                                                                                      oke gass
2    Aplikasi andalan kalau mau pergi-pergi. Nyari drivernya cepet banget, gak pake nunggu lama langsung dapet. Abang drivernya juga ramah-ramah dan amanah. sama kadang suka pesen makanan juga, mudah banget.
3                                                                                                                                                                                                          good
4                                                                                                                              semakin kesini semakin ga ngotak tarifnya. keterlaluan ambil potongan ke driver.
Name: content, dtype: object

In [10]:
# Cek missing value
print(f"Jumlah missing value pada kolom 'content': {df_grab_test['content'].isnull().sum()}")

Jumlah missing value pada kolom 'content': 0

### Preprocesing

#### Cleaning

In [14]:
# Membersihkan String
df_grab_test['step1_string'] = df_grab_test['content'].apply(clean_string)

# Olah token dan normalisasinya
df_grab_test['clean_content'] = df_grab_test['step1_string'].apply(process_tokens)

# Perbandingannya
print(df_grab_test[['content', 'clean_content']].head(100))

                                                                                                                                                                                                       content  \
0                                                                                                                                                                                              sangat membantu
1                                                                                                                                                                                                     oke gass
2   Aplikasi andalan kalau mau pergi-pergi. Nyari drivernya cepet banget, gak pake nunggu lama langsung dapet. Abang drivernya juga ramah-ramah dan amanah. sama kadang suka pesen makanan juga, mudah banget.
3                                                                                                                                                                                                         good
4                                                                                                                             semakin kesini semakin ga ngotak tarifnya. keterlaluan ambil potongan ke driver.
..                                                                                                                                                                                                         ...
95                                                       sempat download karna urgent terus sekarang lagi urgent juga tapi liat harga layanan sepeda motor mahal banget padahal deket banget jadi gak worth it
96                           tolong bantuin kepala saya, saya ingin sekali menjadi mitra driver grab tapi di kota malang tidak di buka pendaftaran lagi di aplikasi tapi menerima driver baru secara pribadi 🙏
97                                                                                                                                                                      Lumayan, perlu perbaikan lebih lanjut.
98                                                                                                                                                                                                    membantu
99                                                                                                                                                                                              baik dan ramah

                                                                                                                                     clean_content
0
1                                                                                                                                         oke gass
2   aplikasi andalan pergi pergi drivernya cepat banget gak pakai nunggu abang drivernya ramah ramah amanah kadang suka pesen makanan mudah banget
3                                                                                                                                             good
4                                                                                                  kesini ga ngotak tarifnya ambil potongan driver
..                                                                                                                                             ...
95                                                  download urgent urgent lihat harga layanan sepeda motor mahal banget deket banget gak worth it
96                                            bantuin kepala mitra driver grab kota malang tidak buka pendaftaran aplikasi menerima driver pribadi
97                                                                                                                               lumayan perbaikan
98
99                                                                                                                                           ramah

[100 rows x 2 columns]

#### Labeling

In [15]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from deep_translator import GoogleTranslator
from tqdm import tqdm

# Inisialisasi SentimentIntensityAnalyzer dan GoogleTranslator
analyzer = SentimentIntensityAnalyzer()
translator = GoogleTranslator(source='id', target='en')

tanyain_teks = df_grab_test['clean_content'].fillna("").astype(str).tolist()

hasil_terjemahan = []
batch_size = 100

print("Memulai proses translasi berbasis batch...")
for i in tqdm(range(0, len(tanyain_teks), batch_size)):
    batch = tanyain_teks[i:i+batch_size]
    try:
        # Masukkan list berisi 100 teks, hasil outputnya juga list berisi 100 terjemahan
        translated_batch = translator.translate_batch(batch)
        hasil_terjemahan.extend(translated_batch)
    except Exception as e:
        # Jaring pengaman jika satu batch gagal, isi dengan teks kosong agar ukuran list tetap singkron
        hasil_terjemahan.extend([""] * len(batch))

Memulai proses translasi berbasis batch...

100%|██████████| 100/100 [2:36:17<00:00, 93.78s/it]

In [16]:
def hitung_vader_dari_en(teks_en):
    if not teks_en or teks_en.strip() == "":
        return 'netral'
    scores = analyzer.polarity_scores(teks_en)
    compound = scores['compound']
    if compound >= 0.05: return 'positif'
    elif compound <= -0.05: return 'negatif'
    else: return 'netral'

# Petakan hasil terjemahan langsung ke kolom sentimen
df_grab_test['sentimen'] = [hitung_vader_dari_en(t) for t in hasil_terjemahan]

In [17]:
df_grab_test[['content', 'clean_content', 'sentimen']].head(100)

,content,clean_content,sentimen
0,sangat membantu,,netral
1,oke gass,oke gass,positif
2,"Aplikasi andalan kalau mau pergi-pergi. Nyari drivernya cepet banget, gak pake nunggu lama langsung dapet. Abang drivernya juga ramah-ramah dan amanah. sama kadang suka pesen makanan juga, mudah banget.",aplikasi andalan pergi pergi drivernya cepat banget gak pakai nunggu abang drivernya ramah ramah amanah kadang suka pesen makanan mudah banget,positif
3,good,good,positif
4,semakin kesini semakin ga ngotak tarifnya. keterlaluan ambil potongan ke driver.,kesini ga ngotak tarifnya ambil potongan driver,negatif
...,...,...,...
95,sempat download karna urgent terus sekarang lagi urgent juga tapi liat harga layanan sepeda motor mahal banget padahal deket banget jadi gak worth it,download urgent urgent lihat harga layanan sepeda motor mahal banget deket banget gak worth it,negatif
96,"tolong bantuin kepala saya, saya ingin sekali menjadi mitra driver grab tapi di kota malang tidak di buka pendaftaran lagi di aplikasi tapi menerima driver baru secara pribadi 🙏",bantuin kepala mitra driver grab kota malang tidak buka pendaftaran aplikasi menerima driver pribadi,positif
97,"Lumayan, perlu perbaikan lebih lanjut.",lumayan perbaikan,positif
98,membantu,,netral
99,baik dan ramah,ramah,positif

In [18]:
df_grab_test['sentimen'].value_counts()

sentimen
positif    4953
netral     2853
negatif    2194
Name: count, dtype: int64

In [19]:
df_grab_test.to_csv('grab_review_bersih.csv', index=False)